# Generated by Django 5.1.3 on 2024-11-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('Cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('Edad', models.PositiveSmallIntegerField()),
                ('Saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Activo', models.IntegerField(choices=[(1, 'Activo'), (0, 'Inactivo')], default=1)),
                ('Nivel_de_Satisfaccion', models.IntegerField(choices=[(1, 'Muy Insatisfecho'), (2, 'Insatisfecho'), (3, 'Neutral'), (4, 'Satisfecho'), (5, 'Muy Satisfecho')], default=3)),
            ],
        ),
    ]
